version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Unit Tests
          command: |
            npm test
      - run:
          name: Run Acceptance Tests
          command: |
            npm start & ./node_modules/.bin/cypress verify & cypress cache path & ./node_modules/.bin/cypress run
